package com.mycompany.mavenproject1;
// Generated 06-abr-2019 2:03:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CasoPolicial generated by hbm2java
 */
public class CasoPolicial  implements java.io.Serializable {


     private String codCaso;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;
     private Set colaboras = new HashSet(0);

    public CasoPolicial() {
    }

	
    public CasoPolicial(String codCaso) {
        this.codCaso = codCaso;
    }
    public CasoPolicial(String codCaso, String nombre, Date fechaInicio, Date fechaFin, Set colaboras) {
       this.codCaso = codCaso;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.colaboras = colaboras;
    }
   
    public String getCodCaso() {
        return this.codCaso;
    }
    
    public void setCodCaso(String codCaso) {
        this.codCaso = codCaso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getColaboras() {
        return this.colaboras;
    }
    
    public void setColaboras(Set colaboras) {
        this.colaboras = colaboras;
    }




}


