package com.mycompany.mavenproject1;
// Generated 06-abr-2019 2:03:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ColaboraId generated by hbm2java
 */
public class ColaboraId  implements java.io.Serializable {


     private String codExperto;
     private String codCaso;
     private Date fecha;

    public ColaboraId() {
    }

    public ColaboraId(String codExperto, String codCaso, Date fecha) {
       this.codExperto = codExperto;
       this.codCaso = codCaso;
       this.fecha = fecha;
    }
   
    public String getCodExperto() {
        return this.codExperto;
    }
    
    public void setCodExperto(String codExperto) {
        this.codExperto = codExperto;
    }
    public String getCodCaso() {
        return this.codCaso;
    }
    
    public void setCodCaso(String codCaso) {
        this.codCaso = codCaso;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ColaboraId) ) return false;
		 ColaboraId castOther = ( ColaboraId ) other; 
         
		 return ( (this.getCodExperto()==castOther.getCodExperto()) || ( this.getCodExperto()!=null && castOther.getCodExperto()!=null && this.getCodExperto().equals(castOther.getCodExperto()) ) )
 && ( (this.getCodCaso()==castOther.getCodCaso()) || ( this.getCodCaso()!=null && castOther.getCodCaso()!=null && this.getCodCaso().equals(castOther.getCodCaso()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodExperto() == null ? 0 : this.getCodExperto().hashCode() );
         result = 37 * result + ( getCodCaso() == null ? 0 : this.getCodCaso().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


